// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWDC3N7HQCZ5-eMq4PAny9__VACS9w2A',
    appId: '1:176991952395:web:6b41cb54303e23d595f10e',
    messagingSenderId: '176991952395',
    projectId: 'poling-pplgc',
    authDomain: 'poling-pplgc.firebaseapp.com',
    databaseURL: 'https://poling-pplgc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poling-pplgc.firebasestorage.app',
    measurementId: 'G-EJ77GHD2MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9gT9apYqvWZ_aSERzJevcwnkG7FW9E4',
    appId: '1:176991952395:android:a3fb6e255ac084d895f10e',
    messagingSenderId: '176991952395',
    projectId: 'poling-pplgc',
    databaseURL: 'https://poling-pplgc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poling-pplgc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_l1pAFmtYKPoC4way7htTWOgvRG3pGw',
    appId: '1:176991952395:ios:8614dd6b7ad33dd895f10e',
    messagingSenderId: '176991952395',
    projectId: 'poling-pplgc',
    databaseURL: 'https://poling-pplgc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poling-pplgc.firebasestorage.app',
    iosBundleId: 'com.example.poling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_l1pAFmtYKPoC4way7htTWOgvRG3pGw',
    appId: '1:176991952395:ios:8614dd6b7ad33dd895f10e',
    messagingSenderId: '176991952395',
    projectId: 'poling-pplgc',
    databaseURL: 'https://poling-pplgc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poling-pplgc.firebasestorage.app',
    iosBundleId: 'com.example.poling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbWDC3N7HQCZ5-eMq4PAny9__VACS9w2A',
    appId: '1:176991952395:web:3a171cf7649cf95895f10e',
    messagingSenderId: '176991952395',
    projectId: 'poling-pplgc',
    authDomain: 'poling-pplgc.firebaseapp.com',
    databaseURL: 'https://poling-pplgc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poling-pplgc.firebasestorage.app',
    measurementId: 'G-HK2D8ZFV7P',
  );

}